export const ADD_TO_CART ="ADD_TO_CART";
export const DELETE_FROM_CART ="DELETE_FROM_CART";
export const SEARCH_BAR ="SEARCH_BAR";
export const ADD_TO_WISHLIST ="ADD_TO_WISHLIST";
export const DELETE_FROM_WISHLIST ="DELETE_FROM_WISHLIST";
export const ADJUST_QUANTITY= "ADJUST_QUANTITY";
export const INCREMENT_QUANTITY= "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY= "DECREMENT_QUANTITY";